## Summarize total counts of trash by high-level categories for MDMAP dataset

In [1]:
import pandas as pd
import numpy as np
import json
import seaborn as sns

Import `category_map.csv` and create a dictionary:

In [2]:
cat_map = pd.read_csv('category_map.csv')
catdict = {key:value for key,value in zip(cat_map['Column Name'], cat_map['High-Level Category'])}

Import TIDES data

In [33]:
tides_all = pd.read_csv('data_processed/TIDES_detailed_summary_earth_cleaned.csv')
tides_all.head(20)

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,LAT,LONG,Meters
0,14,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-11,NaN,1.0,0.0,...,0,0,0,0,0,0,5.0,NaN,NaN,0.000000
1,17,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,2.0,0.0,...,0,0,0,0,0,0,5.0,NaN,NaN,0.000000
2,18,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,1.0,0.0,...,0,0,0,0,0,2,6.0,NaN,NaN,0.000000
3,21,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,1.0,0.0,...,0,0,0,0,0,1,33.0,NaN,NaN,0.000000
4,22,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,1.0,0.0,...,0,0,0,0,0,2,39.0,NaN,NaN,0.000000
5,24,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-11,NaN,1.0,0.0,...,0,0,0,0,0,0,5.0,NaN,NaN,0.000000
6,25,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-29,NaN,1.0,0.0,...,0,0,0,0,0,0,4.0,NaN,NaN,0.000000
7,58,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-12-03,NaN,1.0,0.0,...,0,0,0,0,0,0,5.0,NaN,NaN,0.000000
8,77,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-12-13,NaN,1.0,0.0,...,0,0,0,0,0,31,163.0,NaN,NaN,0.000000
9,78,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-12-13,NaN,1.0,0.0,...,0,0,0,0,0,24,50.0,NaN,NaN,0.000000
10,86,"Cuyahoga County, OH, USA","Ohio, USA",United States,"41.49742, -81.56505","Land (beach, shoreline and inland)",2014-12-22,NaN,1.0,0.0,...,0,0,0,0,0,0,3.0,41.49742,-81.56505,14.484060
11,87,"Fairfax County, VA, USA","Virginia, USA",United States,"38.87456, -77.24428","Land (beach, shoreline and inland)",2014-12-24,NaN,1.0,0.0,...,0,0,0,0,0,2,10.0,38.87456,-77.24428,2237.465402
12,92,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.04405","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,0,0,0,0,4.0,38.90733,-77.04405,34.439876
13,93,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,0,0,0,0,14.0,38.90733,-77.04410,48.602068
14,94,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,0,0,0,0,0,0,14.0,38.90733,-77.04410,48.602068
15,102,"Washington, DC, USA","District of Columbia, USA",United States,"38.90728, -77.04411","Land (beach, shoreline and inland)",2015-03-10,NaN,1.0,0.0,...,0,0,1,0,0,1,17.0,38.90728,-77.04411,227.721610
16,115,"Washington, DC, USA","District of Columbia, USA",United States,"38.90745, -77.04423","Land (beach, shoreline and inland)",2015-03-10,NaN,1.0,0.0,...,0,0,0,0,0,1,5.0,38.90745,-77.04423,37.175754
17,117,"Washington, DC, USA","District of Columbia, USA",United States,"38.9074, -77.04382","Land (beach, shoreline and inland)",2015-03-18,NaN,1.0,0.0,...,0,0,0,0,0,0,8.0,38.90740,-77.04382,64.051732
18,121,"Washington, DC, USA","District of Columbia, USA",United States,"38.90756, -77.04415","Land (beach, shoreline and inland)",2015-03-24,NaN,1.0,0.0,...,0,0,0,0,0,2,10.0,38.90756,-77.04415,117.481820
19,122,"Washington, DC, USA","District of Columbia, USA",United States,"38.90738, -77.04383","Land (beach, shoreline and inland)",2015-03-24,NaN,1.0,0.0,...,0,0,1,0,0,0,10.0,38.90738,-77.04383,1054.439568

Map MDMAP trash subcategories to their corresponding `High-Level Category`:

In [11]:
tides_long = pd.melt(tides_all, id_vars=['Cleanup ID'],
                     value_vars=['Cigarette Butts',
                                 'Food Wrappers (candy, chips, etc.)',
                                 'Take Out/Away Containers (Plastic)',
                                 'Take Out/Away Containers (Foam)',
                                 'Bottle Caps (Plastic)',
                                 'Bottle Caps (Metal)',
                                 'Lids (Plastic)',
                                 'Straws, Stirrers',
                                 'Forks, Knives, Spoons',
                                 'Beverage Bottles (Plastic)',
                                 'Beverage Bottles (Glass)',
                                 'Beverage Cans',
                                 'Grocery Bags (Plastic)',
                                 'Other Plastic Bags',
                                 'Paper Bags',
                                 'Cups, Plates (Paper)',
                                 'Cups, Plates (Plastic)',
                                 'Cups, Plates (Foam)',
                                 'Fishing Buoys, Pots & Traps',
                                 'Fishing Net & Pieces',
                                 'Fishing Line (1 yard/meter = 1 piece)',
                                 'Rope (1 yard/meter = 1 piece)',
                                 'Fishing Gear (Clean Swell)',
                                 '6-Pack Holders',
                                 'Other Plastic/Foam Packaging',
                                 'Other Plastic Bottles (oil, bleach, etc.)',
                                 'Strapping Bands',
                                 'Tobacco Packaging/Wrap',
                                 'Other Packaging (Clean Swell)',
                                 'Appliances (refrigerators, washers, etc.)',
                                 'Balloons',
                                 'Cigar Tips',
                                 'Cigarette Lighters',
                                 'Construction Materials',
                                 'Fireworks',
                                 'Tires',
                                 'Toys',
                                 'Other Trash (Clean Swell)',
                                 'Condoms',
                                 'Diapers',
                                 'Syringes',
                                 'Tampons/Tampon Applicators',
                                 'Personal Hygiene (Clean Swell)',
                                 'Foam Pieces',
                                 'Glass Pieces',
                                 'Plastic Pieces'], 
                     var_name='Subcategory', value_name='Count')

In [12]:
tides_long

        Cleanup ID      Subcategory     Count
0               14  Cigarette Butts         0
1               17  Cigarette Butts         0
2               18  Cigarette Butts         0
3               21  Cigarette Butts        17
4               22  Cigarette Butts        17
5               24  Cigarette Butts         0
6               25  Cigarette Butts         0
7               58  Cigarette Butts         0
8               77  Cigarette Butts         7
9               78  Cigarette Butts         0
10              86  Cigarette Butts         0
11              87  Cigarette Butts         1
12              92  Cigarette Butts         0
13              93  Cigarette Butts         1
14              94  Cigarette Butts         1
15             102  Cigarette Butts         0
16             115  Cigarette Butts         1
17             117  Cigarette Butts         0
18             121  Cigarette Butts         2
19             122  Cigarette Butts         0
20             123  Cigarette Butts         4
21             125  Cigarette Butts         0
22             126  Cigarette Butts         0
23             129  Cigarette Butts         0
24             130  Cigarette Butts         0
25             134  Cigarette Butts         1
26             135  Cigarette Butts         0
27             136  Cigarette Butts         0
28             137  Cigarette Butts         0
29             138  Cigarette Butts         0
...            ...              ...       ...
2732600      71869   Plastic Pieces         0
2732601      71870   Plastic Pieces         1
2732602      71871   Plastic Pieces         0
2732603      71872   Plastic Pieces         7
2732604      71873   Plastic Pieces         5
2732605      71874   Plastic Pieces         0
2732606      71875   Plastic Pieces         0
2732607      71876   Plastic Pieces        79
2732608      71877   Plastic Pieces         0
2732609      71878   Plastic Pieces         0
2732610      71879   Plastic Pieces        15
2732611      71880   Plastic Pieces         0
2732612      71881   Plastic Pieces         4
2732613      71882   Plastic Pieces         1
2732614      71883   Plastic Pieces         0
2732615      71884   Plastic Pieces         1
2732616      71885   Plastic Pieces         0
2732617      71886   Plastic Pieces         0
2732618      71887   Plastic Pieces         0
2732619      71888   Plastic Pieces        14
2732620      71889   Plastic Pieces       127
2732621      71890   Plastic Pieces        61
2732622      71891   Plastic Pieces         2
2732623      71892   Plastic Pieces         1
2732624      71893   Plastic Pieces        77
2732625      71894   Plastic Pieces         1
2732626      71895   Plastic Pieces        41
2732627      71896   Plastic Pieces         0
2732628      71897   Plastic Pieces         3
2732629    Totals:   Plastic Pieces  49936102

[2732630 rows x 3 columns]

In [13]:
# Remove non-numerical values under Count
tides_int = tides_long[tides_long.applymap(np.isreal).Count]
tides_int

        Cleanup ID      Subcategory     Count
0               14  Cigarette Butts         0
1               17  Cigarette Butts         0
2               18  Cigarette Butts         0
3               21  Cigarette Butts        17
4               22  Cigarette Butts        17
5               24  Cigarette Butts         0
6               25  Cigarette Butts         0
7               58  Cigarette Butts         0
8               77  Cigarette Butts         7
9               78  Cigarette Butts         0
10              86  Cigarette Butts         0
11              87  Cigarette Butts         1
12              92  Cigarette Butts         0
13              93  Cigarette Butts         1
14              94  Cigarette Butts         1
15             102  Cigarette Butts         0
16             115  Cigarette Butts         1
17             117  Cigarette Butts         0
18             121  Cigarette Butts         2
19             122  Cigarette Butts         0
20             123  Cigarette Butts         4
21             125  Cigarette Butts         0
22             126  Cigarette Butts         0
23             129  Cigarette Butts         0
24             130  Cigarette Butts         0
25             134  Cigarette Butts         1
26             135  Cigarette Butts         0
27             136  Cigarette Butts         0
28             137  Cigarette Butts         0
29             138  Cigarette Butts         0
...            ...              ...       ...
2732600      71869   Plastic Pieces         0
2732601      71870   Plastic Pieces         1
2732602      71871   Plastic Pieces         0
2732603      71872   Plastic Pieces         7
2732604      71873   Plastic Pieces         5
2732605      71874   Plastic Pieces         0
2732606      71875   Plastic Pieces         0
2732607      71876   Plastic Pieces        79
2732608      71877   Plastic Pieces         0
2732609      71878   Plastic Pieces         0
2732610      71879   Plastic Pieces        15
2732611      71880   Plastic Pieces         0
2732612      71881   Plastic Pieces         4
2732613      71882   Plastic Pieces         1
2732614      71883   Plastic Pieces         0
2732615      71884   Plastic Pieces         1
2732616      71885   Plastic Pieces         0
2732617      71886   Plastic Pieces         0
2732618      71887   Plastic Pieces         0
2732619      71888   Plastic Pieces        14
2732620      71889   Plastic Pieces       127
2732621      71890   Plastic Pieces        61
2732622      71891   Plastic Pieces         2
2732623      71892   Plastic Pieces         1
2732624      71893   Plastic Pieces        77
2732625      71894   Plastic Pieces         1
2732626      71895   Plastic Pieces        41
2732627      71896   Plastic Pieces         0
2732628      71897   Plastic Pieces         3
2732629    Totals:   Plastic Pieces  49936102

[2732630 rows x 3 columns]

In [16]:
tides_int = tides_int.dropna()
tides_int.Count = tides_int.Count.astype('int64')
tides_int['Category'] = tides_int['Subcategory'].map(catdict)
tides_int

        Cleanup ID      Subcategory     Count Category
0               14  Cigarette Butts         0    Other
1               17  Cigarette Butts         0    Other
2               18  Cigarette Butts         0    Other
3               21  Cigarette Butts        17    Other
4               22  Cigarette Butts        17    Other
5               24  Cigarette Butts         0    Other
6               25  Cigarette Butts         0    Other
7               58  Cigarette Butts         0    Other
8               77  Cigarette Butts         7    Other
9               78  Cigarette Butts         0    Other
10              86  Cigarette Butts         0    Other
11              87  Cigarette Butts         1    Other
12              92  Cigarette Butts         0    Other
13              93  Cigarette Butts         1    Other
14              94  Cigarette Butts         1    Other
15             102  Cigarette Butts         0    Other
16             115  Cigarette Butts         1    Other
17             117  Cigarette Butts         0    Other
18             121  Cigarette Butts         2    Other
19             122  Cigarette Butts         0    Other
20             123  Cigarette Butts         4    Other
21             125  Cigarette Butts         0    Other
22             126  Cigarette Butts         0    Other
23             129  Cigarette Butts         0    Other
24             130  Cigarette Butts         0    Other
25             134  Cigarette Butts         1    Other
26             135  Cigarette Butts         0    Other
27             136  Cigarette Butts         0    Other
28             137  Cigarette Butts         0    Other
29             138  Cigarette Butts         0    Other
...            ...              ...       ...      ...
2732600      71869   Plastic Pieces         0  Plastic
2732601      71870   Plastic Pieces         1  Plastic
2732602      71871   Plastic Pieces         0  Plastic
2732603      71872   Plastic Pieces         7  Plastic
2732604      71873   Plastic Pieces         5  Plastic
2732605      71874   Plastic Pieces         0  Plastic
2732606      71875   Plastic Pieces         0  Plastic
2732607      71876   Plastic Pieces        79  Plastic
2732608      71877   Plastic Pieces         0  Plastic
2732609      71878   Plastic Pieces         0  Plastic
2732610      71879   Plastic Pieces        15  Plastic
2732611      71880   Plastic Pieces         0  Plastic
2732612      71881   Plastic Pieces         4  Plastic
2732613      71882   Plastic Pieces         1  Plastic
2732614      71883   Plastic Pieces         0  Plastic
2732615      71884   Plastic Pieces         1  Plastic
2732616      71885   Plastic Pieces         0  Plastic
2732617      71886   Plastic Pieces         0  Plastic
2732618      71887   Plastic Pieces         0  Plastic
2732619      71888   Plastic Pieces        14  Plastic
2732620      71889   Plastic Pieces       127  Plastic
2732621      71890   Plastic Pieces        61  Plastic
2732622      71891   Plastic Pieces         2  Plastic
2732623      71892   Plastic Pieces         1  Plastic
2732624      71893   Plastic Pieces        77  Plastic
2732625      71894   Plastic Pieces         1  Plastic
2732626      71895   Plastic Pieces        41  Plastic
2732627      71896   Plastic Pieces         0  Plastic
2732628      71897   Plastic Pieces         3  Plastic
2732629    Totals:   Plastic Pieces  49936102  Plastic

[2732630 rows x 4 columns]

In [19]:
# Calculate the total counts by the High-Level Category:
tides_group = tides_int.groupby(['Cleanup ID','Category'], as_index=False).sum()
tides_group

       Cleanup ID          Category      Count
0              14      Fishing Gear          0
1              14             Glass          1
2              14             Metal          0
3              14             Other          1
4              14           Plastic          3
5              14  Processed Lumber          0
6              14            Rubber          0
7              17      Fishing Gear          1
8              17             Glass          0
9              17             Metal          0
10             17             Other          1
11             17           Plastic          3
12             17  Processed Lumber          0
13             17            Rubber          0
14             18      Fishing Gear          1
15             18             Glass          0
16             18             Metal          0
17             18             Other          1
18             18           Plastic          3
19             18  Processed Lumber          1
20             18            Rubber          0
21             21      Fishing Gear          0
22             21             Glass          0
23             21             Metal          1
24             21             Other         19
25             21           Plastic         11
26             21  Processed Lumber          2
27             21            Rubber          0
28             22      Fishing Gear          0
29             22             Glass          1
...           ...               ...        ...
415805      71894  Processed Lumber          0
415806      71894            Rubber          0
415807      71895      Fishing Gear          0
415808      71895             Glass          1
415809      71895             Metal          3
415810      71895             Other         15
415811      71895           Plastic         82
415812      71895  Processed Lumber          0
415813      71895            Rubber          0
415814      71896      Fishing Gear          5
415815      71896             Glass          0
415816      71896             Metal          0
415817      71896             Other          0
415818      71896           Plastic          5
415819      71896  Processed Lumber          0
415820      71896            Rubber          0
415821      71897      Fishing Gear          0
415822      71897             Glass          1
415823      71897             Metal          6
415824      71897             Other         49
415825      71897           Plastic         46
415826      71897  Processed Lumber          0
415827      71897            Rubber          0
415828    Totals:      Fishing Gear     964376
415829    Totals:             Glass    5362131
415830    Totals:             Metal    5356474
415831    Totals:             Other   13573121
415832    Totals:           Plastic  111342527
415833    Totals:  Processed Lumber    1435326
415834    Totals:            Rubber     433342

[415835 rows x 3 columns]

In [21]:
tides_totals = tides_group.pivot(index='Cleanup ID', 
                                columns='Category',
                                values='Count')

Merge the key location and survey stats with the trash totals:

In [29]:
# Store the key location and survey stats in a dataframe:
tides_orig = tides_all[['Cleanup ID',
                         'Zone',
                         'State',
                         'Country',
                         'GPS',
                         'Cleanup Type',
                         'Cleanup Date',
                         'Group Name',
                         'Adults',
                         'Children',
                         'People',
                         'Pounds',
                         'Miles',
                         '# of bags',
                         'Total Items Collected',
                         'LAT',
                         'LONG',
                         'Meters']]
tides_orig.head()

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,People,Pounds,Miles,# of bags,Total Items Collected,LAT,LONG,Meters
0,14,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-11,NaN,1.0,0.0,1.0,1.57,0.0,0.0,5.0,NaN,NaN,0.0
1,17,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,2.0,0.0,2.0,1.57,0.0,0.0,5.0,NaN,NaN,0.0
2,18,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,1.0,0.0,1.0,1.64,0.0,0.0,6.0,NaN,NaN,0.0
3,21,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,1.0,0.0,1.0,2.39,0.0,0.0,33.0,NaN,NaN,0.0
4,22,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,1.0,0.0,1.0,3.99,0.0,0.0,39.0,NaN,NaN,0.0

In [37]:
# Merge with map_totals:

# Test:
tides_final = pd.merge(tides_orig, tides_totals, how='outer', on='Cleanup ID', indicator=True)
tides_final = tides_final.drop('_merge', 1)
tides_final.head(20)

,Cleanup ID,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,LAT,LONG,Meters,Fishing Gear,Glass,Metal,Other,Plastic,Processed Lumber,Rubber
0,14,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-11,NaN,1.0,0.0,...,NaN,NaN,0.000000,0,1,0,1,3,0,0
1,17,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,2.0,0.0,...,NaN,NaN,0.000000,1,0,0,1,3,0,0
2,18,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,1.0,0.0,...,NaN,NaN,0.000000,1,0,0,1,3,1,0
3,21,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,1.0,0.0,...,NaN,NaN,0.000000,0,0,1,19,11,2,0
4,22,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-10,NaN,1.0,0.0,...,NaN,NaN,0.000000,0,1,0,20,18,0,0
5,24,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-11,NaN,1.0,0.0,...,NaN,NaN,0.000000,0,1,0,1,3,0,0
6,25,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-10-29,NaN,1.0,0.0,...,NaN,NaN,0.000000,2,0,0,0,1,1,0
7,58,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-12-03,NaN,1.0,0.0,...,NaN,NaN,0.000000,0,0,1,0,3,0,1
8,77,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-12-13,NaN,1.0,0.0,...,NaN,NaN,0.000000,1,21,7,25,99,10,0
9,78,NaN,NaN,NaN,NaN,"Land (beach, shoreline and inland)",2014-12-13,NaN,1.0,0.0,...,NaN,NaN,0.000000,0,1,1,7,35,6,0
10,86,"Cuyahoga County, OH, USA","Ohio, USA",United States,"41.49742, -81.56505","Land (beach, shoreline and inland)",2014-12-22,NaN,1.0,0.0,...,41.49742,-81.56505,14.484060,0,0,1,0,1,0,1
11,87,"Fairfax County, VA, USA","Virginia, USA",United States,"38.87456, -77.24428","Land (beach, shoreline and inland)",2014-12-24,NaN,1.0,0.0,...,38.87456,-77.24428,2237.465402,1,0,1,1,6,1,0
12,92,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.04405","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,38.90733,-77.04405,34.439876,0,0,0,1,3,0,0
13,93,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,38.90733,-77.04410,48.602068,0,0,0,1,13,0,0
14,94,"Washington, DC, USA","District of Columbia, USA",United States,"38.90733, -77.0441","Land (beach, shoreline and inland)",2015-02-19,NaN,1.0,0.0,...,38.90733,-77.04410,48.602068,0,0,0,1,13,0,0
15,102,"Washington, DC, USA","District of Columbia, USA",United States,"38.90728, -77.04411","Land (beach, shoreline and inland)",2015-03-10,NaN,1.0,0.0,...,38.90728,-77.04411,227.721610,1,2,2,3,9,0,0
16,115,"Washington, DC, USA","District of Columbia, USA",United States,"38.90745, -77.04423","Land (beach, shoreline and inland)",2015-03-10,NaN,1.0,0.0,...,38.90745,-77.04423,37.175754,0,0,1,1,3,0,0
17,117,"Washington, DC, USA","District of Columbia, USA",United States,"38.9074, -77.04382","Land (beach, shoreline and inland)",2015-03-18,NaN,1.0,0.0,...,38.90740,-77.04382,64.051732,0,1,1,0,6,0,0
18,121,"Washington, DC, USA","District of Columbia, USA",United States,"38.90756, -77.04415","Land (beach, shoreline and inland)",2015-03-24,NaN,1.0,0.0,...,38.90756,-77.04415,117.481820,0,1,1,2,4,1,1
19,122,"Washington, DC, USA","District of Columbia, USA",United States,"38.90738, -77.04383","Land (beach, shoreline and inland)",2015-03-24,NaN,1.0,0.0,...,38.90738,-77.04383,1054.439568,0,1,1,5,3,0,0

### Save to file.

In [38]:
tides_final.to_csv('data_processed/TIDES_earth_totals_by_category.csv', index=False)

In [39]:
list(tides_final)

['Cleanup ID',
 'Zone',
 'State',
 'Country',
 'GPS',
 'Cleanup Type',
 'Cleanup Date',
 'Group Name',
 'Adults',
 'Children',
 'People',
 'Pounds',
 'Miles',
 '# of bags',
 'Total Items Collected',
 'LAT',
 'LONG',
 'Meters',
 'Fishing Gear',
 'Glass',
 'Metal',
 'Other',
 'Plastic',
 'Processed Lumber',
 'Rubber']